### ISSUE TITLE
Lost Connection Device, App crash

### ISSUE THREAD

**Issue by AnByron** [kilroy80/flutter_video_360#15]
When I reproduce the example, my app crash.
This is the outup on my console:

I/Video360ViewFactory(17762): 0
I/Video360ViewFactory(17762): {}
I/PlatformViewsController(17762): Using hybrid composition for platform view: 0
I/ExoPlayerImpl(17762): Init 34f9047 [ExoPlayerLib/2.18.1] [generic_x86, Android SDK built for x86, Google, 29]
W/pp_semana_sant(17762): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
E/AndroidRuntime(17762): FATAL EXCEPTION: main
E/AndroidRuntime(17762): Process: com.example.app_semana_santa, PID: 17762
E/AndroidRuntime(17762): java.lang.NoSuchMethodError: No interface method getCurrentTracksInfo()Lcom/google/android/exoplayer2/TracksInfo; in class Lcom/google/android/exoplayer2/Player; or its super classes (declaration of 'com.google.android.exoplayer2.Player' appears in /data/app/com.example.app_semana_santa-N2uXvmHTaffeamTcX8V1TQ==/base.apk!classes2.dex)
E/AndroidRuntime(17762): 	at com.google.android.exoplayer2.ui.StyledPlayerView.updateForCurrentTrackSelections(StyledPlayerView.java:1197)
E/AndroidRuntime(17762): 	at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:510)
E/AndroidRuntime(17762): 	at com.kino.video_360.Video360UIView.initializePlayer(Video360UIView.kt:136)
E/AndroidRuntime(17762): 	at com.kino.video_360.Video360View.onMethodCall(Video360View.kt:53)
E/AndroidRuntime(17762): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(17762): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(17762): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(17762): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(17762): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(17762): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17762): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17762): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(17762): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17762): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(17762): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (17762): Sending signal. PID: 17762 SIG: 9
Lost connection to device.
Exited (sigterm)

I have the last version of Flutter:
flutter --version
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (6 days ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

And in Flutter doctor everything it's ok.

**Comment by kilroy80** [comment]
Using Android Exoplayer version 2.17.
I'm going to test the higher version later
