### ISSUE TITLE
App crashes when playing the video.

### ISSUE THREAD

**Issue by ms471841** [kilroy80/flutter_video_360#19]
## The Error any solution for it?
 @kilroy80 @irvine5k @Up-s @medbenzekri 

I/Video360ViewFactory(22582): 0
I/Video360ViewFactory(22582): {}
I/PlatformViewsController(22582): Using hybrid composition for platform view: 0
I/ExoPlayerImpl(22582): Init 49bbe2a [ExoPlayerLib/2.18.7] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
W/m.example.akom(22582): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
E/AndroidRuntime(22582): FATAL EXCEPTION: main
E/AndroidRuntime(22582): Process: com.example.akomo, PID: 22582
E/AndroidRuntime(22582): java.lang.NoSuchMethodError: No interface method getCurrentTracksInfo()Lcom/google/android/exoplayer2/TracksInfo; in class Lcom/google/android/exoplayer2/Player; or its super classes (declaration of 'com.google.android.exoplayer2.Player' appears in /data/app/com.example.akomo-cpYgDOCHJMPQMEEl0k3pvQ==/base.apk!classes3.dex)
E/AndroidRuntime(22582): 	at com.google.android.exoplayer2.ui.StyledPlayerView.updateForCurrentTrackSelections(StyledPlayerView.java:1209)
E/AndroidRuntime(22582): 	at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:522)
E/AndroidRuntime(22582): 	at com.kino.video_360.Video360UIView.initializePlayer(Video360UIView.kt:136)
E/AndroidRuntime(22582): 	at com.kino.video_360.Video360View.onMethodCall(Video360View.kt:53)
E/AndroidRuntime(22582): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(22582): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(22582): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(22582): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(22582): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(22582): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22582): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(22582): 	at android.app.ActivityThread.main(ActivityThread.java:6758)
E/AndroidRuntime(22582): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22582): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime(22582): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
I/System.out(22582): port:443
D/OpenSSLLib(22582): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
D/OpenSSLLib(22582): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
W/AudioCapabilities(22582): Unsupported mime audio/x-adpcm-ms
W/AudioCapabilities(22582): Unsupported mime audio/x-adpcm-dvi-ima
W/AudioCapabilities(22582): Unsupported mime audio/alac
W/AudioCapabilities(22582): Unsupported mime audio/ape
W/VideoCapabilities(22582): Unsupported mime video/divx
W/VideoCapabilities(22582): Unsupported mime video/divx3
W/VideoCapabilities(22582): Unrecognized profile 4 for video/hevc
W/VideoCapabilities(22582): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(22582): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(22582): Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities(22582): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(22582): Unsupported mime video/xvid
W/VideoCapabilities(22582): Unrecognized profile/level 1/32 for video/mp4v-es
I/VideoCapabilities(22582): Unsupported profile 4 for video/mp4v-es
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 3840x1920@-1.0] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 3840x1920@-1.0] [OMX.google.h264.decoder, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 2160x1080@-1.0] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 2160x1080@-1.0] [OMX.google.h264.decoder, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 3840x1920@-1.0] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 3840x1920@-1.0] [OMX.google.h264.decoder, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 2160x1080@-1.0] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
D/MediaCodecInfo(22582): NoSupport [sizeAndRate.support, 2160x1080@-1.0] [OMX.google.h264.decoder, video/avc] [Infinix-X626, Infinix X626, INFINIX MOBILITY LIMITED, 28]
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
I/System.out(22582): port:443
D/OpenSSLLib(22582): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
D/OpenSSLLib(22582): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
I/System.out(22582): [OkHttp] sendRequest>>
I/System.out(22582): [OkHttp] sendRequest<<
W/m.example.akom(22582): Accessing hidden method Landroid/media/MediaFormat;->getInteger(Ljava/lang/String;I)I (dark greylist, linking)
I/BufferQueue(22582): [unnamed-22582-0](this:0x7a9ac3b000,id:0,api:0,p:-1,c:-1) BufferQueue core=(22582:com.example.akomo)
W/ExoPlayer:Place(22582): type=1400 audit(0.0:241841): avc: denied { read } for name="u:object_r:graphics_debug_prop:s0" dev="tmpfs" ino=222 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:graphics_debug_prop:s0 tclass=file permissive=0
E/libc    (22582): Access denied finding property "vendor.debug.sf.stc_interval"
E/libc    (22582): Access denied finding property "vendor.debug.bq.dump"
W/ExoPlayer:Place(22582): type=1400 audit(0.0:241842): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=179 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/BufferQueueConsumer(22582): [unnamed-22582-0](this:0x7a9ac3b000,id:0,api:0,p:-1,c:22582) connect(C): consumer=(22582:com.example.akomo) controlledByApp=true
W/ExoPlayer:Place(22582): type=1400 audit(0.0:241843): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=179 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (22582): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(22582): [unnamed-22582-0](this:0x7a9ac3b000,id:0,api:0,p:-1,c:22582) setConsumerName: unnamed-22582-0
E/libc    (22582): Access denied finding property "vendor.debug.bq.line"
W/ExoPlayer:Place(22582): type=1400 audit(0.0:241844): avc: denied { read } for name="u:object_r:graphics_debug_prop:s0" dev="tmpfs" ino=222 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:graphics_debug_prop:s0 tclass=file permissive=0
E/libc    (22582): Access denied finding property "vendor.debug.bq.line"
I/OMXClient(22582): IOmx service obtained
D/SurfaceUtils(22582): connecting to surface 0x7aacbdc010, reason connectToSurface
D/Surface (22582): Surface::connect(this=0x7aacbdc000,api=3)
I/BufferQueueProducer(22582): [SurfaceTexture-1-22582-0](this:0x7a9ac3b000,id:0,api:3,p:22582,c:22582) connect(P): api=3 producer=(22582:com.example.akomo) producerControlledByApp=true
W/MediaCodec_loop(22582): type=1400 audit(0.0:241847): avc: denied { read } for name="u:object_r:graphics_debug_prop:s0" dev="tmpfs" ino=222 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:graphics_debug_prop:s0 tclass=file permissive=0
E/libc    (22582): Access denied finding property "vendor.debug.bq.line"
I/MediaCodec(22582): [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 23123969
D/SurfaceUtils(22582): disconnecting from surface 0x7aacbdc010, reason connectToSurface(reconnect)
D/Surface (22582): Surface::disconnect(this=0x7aacbdc000,api=3)
I/BufferQueueProducer(22582): [SurfaceTexture-1-22582-0](this:0x7a9ac3b000,id:0,api:3,p:22582,c:22582) disconnect(P): api 3
D/BufferQueueConsumer(22582): [SurfaceTexture-1-22582-0](this:0x7a9ac3b000,id:0,api:3,p:-1,c:22582) getReleasedBuffers: returning mask 0xffffffffffffffff
D/SurfaceUtils(22582): connecting to surface 0x7aacbdc010, reason connectToSurface(reconnect)
D/Surface (22582): Surface::connect(this=0x7aacbdc000,api=3)
I/BufferQueueProducer(22582): [SurfaceTexture-1-22582-0](this:0x7a9ac3b000,id:0,api:3,p:22582,c:22582) connect(P): api=3 producer=(22582:com.example.akomo) producerControlledByApp=true
E/libc    (22582): Access denied finding property "vendor.debug.bq.line"
I/ACodec  (22582): codec does not support config priority (err -1010)
I/ACodec_vilte(22582): setMTKParameters, width: 720
I/ACodec_vilte(22582): setMTKParameters, height: 360
Lost connection to device.

Exited.

**Comment by jingyuan2017** [comment]
Hi , I have a same error , on meta quest2

**Comment by ms471841** [comment]
yeah, any solution for it ?
